name: Test API Validation
# Este evento permite que el workflow sea llamado desde otros repositorios
on:
  workflow_call:

jobs:
  unit-tests:
    name: Ejecutar Pruebas Unitarias
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el código del repositorio cliente
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Jest
        run: npm test
